name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  review:
    timeout-minutes: 90
    runs-on: ubuntu-latest
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.AI_API_KEY }}
          # Optional
          LANGUAGE: English
          OPENAI_API_ENDPOINT: https://integrate.api.nvidia.com/v1
          MODEL: deepseek-ai/deepseek-r1-distill-llama-8b
        #   PROMPT: |
        #     Запрос на код-ревью. Пожалуйста, помоги выявить:
        #     * Любые логические ошибки, баги или упущения.
        #     * Неоптимальные участки кода или потенциальные проблемы с производительностью.
        #     * Уязвимости безопасности.
        #     * Отклонения от стандартов кодирования или лучших практик.
        #     * Места, которые могут быть сложны для понимания или поддержки.
          top_p: 1 # https://platform.openai.com/docs/api-reference/chat/create#chat/create-top_p
          temperature: 1 # https://platform.openai.com/docs/api-reference/chat/create#chat/create-temperature
          IGNORE_PATTERNS: /depedencies/*,*.md # glob pattern or regex pattern to ignore files, separated by comma
          INCLUDE_PATTERNS: Qurre*/*,*.cs,*.cs*,*.slnx # glob pattern or regex pattern to include files, separated by comma
